"""create core domain models

Revision ID: 1d204c6d38c0
Revises: 4368e3ecc291
Create Date: 2026-05-29 18:09:30.137338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d204c6d38c0'
down_revision: Union[str, Sequence[str], None] = '4368e3ecc291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=True)
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_name'), 'risk_factors', ['name'], unique=True)
    op.create_table('element_risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('abundance_score', sa.Float(), nullable=True),
    sa.Column('supply_risk_score', sa.Float(), nullable=True),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('recyclability_score', sa.Float(), nullable=True),
    sa.Column('geopolitical_risk_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_id', 'year', name='uq_element_risk_profile_year')
    )
    op.create_index(op.f('ix_element_risk_profiles_element_id'), 'element_risk_profiles', ['element_id'], unique=False)
    op.create_table('material_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'application_id', name='uq_material_application')
    )
    op.create_index(op.f('ix_material_applications_application_id'), 'material_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_material_applications_material_id'), 'material_applications', ['material_id'], unique=False)
    op.alter_column('elements', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('elements', 'atomic_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elements', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_material_elements_element_id'), 'material_elements', ['element_id'], unique=False)
    op.create_index(op.f('ix_material_elements_material_id'), 'material_elements', ['material_id'], unique=False)
    op.create_unique_constraint('uq_material_element', 'material_elements', ['material_id', 'element_id'])
    op.add_column('materials', sa.Column('formation_energy_per_atom', sa.Float(), nullable=True))
    op.add_column('materials', sa.Column('source', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'source')
    op.drop_column('materials', 'formation_energy_per_atom')
    op.drop_constraint('uq_material_element', 'material_elements', type_='unique')
    op.drop_index(op.f('ix_material_elements_material_id'), table_name='material_elements')
    op.drop_index(op.f('ix_material_elements_element_id'), table_name='material_elements')
    op.alter_column('elements', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('elements', 'atomic_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('elements', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_material_applications_material_id'), table_name='material_applications')
    op.drop_index(op.f('ix_material_applications_application_id'), table_name='material_applications')
    op.drop_table('material_applications')
    op.drop_index(op.f('ix_element_risk_profiles_element_id'), table_name='element_risk_profiles')
    op.drop_table('element_risk_profiles')
    op.drop_index(op.f('ix_risk_factors_name'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
