"""create initial material tables

Revision ID: 4368e3ecc291
Revises: 
Create Date: 2026-05-28 20:42:30.649034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4368e3ecc291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('atomic_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_symbol'), 'elements', ['symbol'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.String(length=50), nullable=False),
    sa.Column('formula', sa.String(length=100), nullable=False),
    sa.Column('pretty_formula', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('band_gap', sa.Float(), nullable=True),
    sa.Column('energy_above_hull', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_mp_id'), 'materials', ['mp_id'], unique=True)
    op.create_table('material_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('fraction', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_elements')
    op.drop_index(op.f('ix_materials_mp_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_elements_symbol'), table_name='elements')
    op.drop_table('elements')
    # ### end Alembic commands ###
